version: "3.9"

services:
  database:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
       - ./docs/SCHEMA.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - appNetwork

  api:
    image: node:16
    env_file: .env
    build:
      context: .
    depends_on:
      - database
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    restart: unless-stopped
    networks:
      - appNetwork

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "${PG_PORT}:80"
    depends_on:
      - database
    networks:
      - appNetwork

networks:
  appNetwork:
    driver: bridge