version: "3.9"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5433:5432'
    networks:
      - appNetwork
  api:
    image: node:16
    build:
      context: .
    depends_on:
      - database
    ports:
      - '${SERVER_PORT}:3000'
    restart: unless-stopped
    networks:
      - appNetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "${PG_PORT}:80"
    depends_on:
      - database
    networks:
      - appNetwork

networks:
  appNetwork:
    driver: bridge