@hostname = localhost
@port = 1234
@host = {{hostname}}:{{port}}



###
POST http://{{host}}/health



###
GET http://{{host}}/restaurants


### {GET} RESTAURANTE ESPECIFICO VÁLIDO
GET http://{{host}}/restaurants/1

### {GET} RESTAURANTE ESPECIFICO INVÁLIDO
GET http://{{host}}/restaurants/999



### {GET} PRODUTOS DE UM RESTAURANTE ESPECIFICO VÁLIDO
GET http://{{host}}/restaurants/1/products

### {GET} PRODUTOS DE UM RESTAURANTE ESPECIFICO INVÁLIDO
GET http://{{host}}/restaurants/9999/products



### {GET} DADOS DE UM PRODUTO UNICO VÁLIDO
GET http://{{host}}/products/1

### {GET} DADOS DE UM PRODUTO UNICO INVÁLIDO
GET http://{{host}}/products/9999



### {GET} EXTRAS DE UM PRODUTO UNICO VÁLIDO
GET http://{{host}}/products/1/extras

### {GET} EXTRAS DE UM PRODUTO UNICO INVÁLIDO
GET http://{{host}}/products/999/extras



### {POST} SALVA UM RESTAURANTE
POST http://{{host}}/restaurants HTTP/1.1
content-type: application/json

{
  "name": "MC Donalds",
  "owner": "Ronald MC Donalds",
  "address": "Rua sem cobertura, 33",
  "description": "Restaurante para comidas frias",
  "image": "https://insira.uma.imagem.aqui.com.br/"
}

### {POST} SALVAR PRODUTO EM UM RESTAURANTE
POST http://{{host}}/restaurants/0000/products/ HTTP/1.1
content-type: application/json

{
  "name": "cheeseburguer",
  "description": "pão, carne e queijo",
  "price": 15.00,
  "image": "https://insira.uma.imagem.aqui.com.br/"
}
